/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "AlarmData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WInfoMO, WInfoMO, AUTO)


PB_BIND(WInfoReqDTO, WInfoReqDTO, 2)


PB_BIND(WInfoResDTO, WInfoResDTO, AUTO)


PB_BIND(WWVDataReqDTO, WWVDataReqDTO, AUTO)


PB_BIND(WWVDataResDTO, WWVDataResDTO, AUTO)



