/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ALARMDATA_PB_H_INCLUDED
#define PB_ALARMDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _WInfoMO {
    int64_t pv_sn; /* PV serial number */
    int32_t WCode; /* WCode identifier */
    int32_t WNum; /* WNum value */
    int32_t WTime1; /* First timestamp value */
    int32_t WTime2; /* Second timestamp value */
    int32_t WData1; /* First data value */
    int32_t WData2; /* Second data value */
} WInfoMO;

typedef struct _WInfoReqDTO {
    char dtu_sn[21]; /* DTU serial number */
    int32_t time; /* Timestamp of the request */
    int32_t package_count;
    int32_t package_idx;
    int32_t warn_device;
    pb_size_t mWInfo_count;
    WInfoMO mWInfo[30]; /* WInfoMO data array */
} WInfoReqDTO;

typedef struct _WInfoResDTO {
    char time_ymd_hms[61]; /* Timestamp in the format YMD_HMS */
    int32_t error_code; /* Error code indicator */
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp value */
} WInfoResDTO;

typedef struct _WWVDataReqDTO {
    char dtu_sn[21]; /* DTU serial number */
    int32_t time; /* Timestamp of the request */
    int32_t package_nub; /* Package number */
    int32_t package_now; /* Current package number */
    int64_t pv_sn; /* PV serial number */
    int32_t WCode; /* WCode identifier */
    int32_t WNum; /* WNum value */
    int32_t WTime1; /* First timestamp value */
    int32_t WVDataL; /* Length of WWVData */
    int32_t WPos; /* WPos value */
    pb_callback_t mWVData; /* WWVData string */
} WWVDataReqDTO;

typedef struct _WWVDataResDTO {
    char time_ymd_hms[61]; /* Timestamp in the format YMD_HMS */
    int32_t package_now; /* Current package number */
    int32_t error_code; /* Error code indicator */
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp value */
} WWVDataResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WInfoMO_init_default                     {0, 0, 0, 0, 0, 0, 0}
#define WInfoReqDTO_init_default                 {"", 0, 0, 0, 0, 0, {WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default}}
#define WInfoResDTO_init_default                 {"", 0, 0, 0}
#define WWVDataReqDTO_init_default               {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define WWVDataResDTO_init_default               {"", 0, 0, 0, 0}
#define WInfoMO_init_zero                        {0, 0, 0, 0, 0, 0, 0}
#define WInfoReqDTO_init_zero                    {"", 0, 0, 0, 0, 0, {WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero}}
#define WInfoResDTO_init_zero                    {"", 0, 0, 0}
#define WWVDataReqDTO_init_zero                  {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define WWVDataResDTO_init_zero                  {"", 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WInfoMO_pv_sn_tag                        1
#define WInfoMO_WCode_tag                        2
#define WInfoMO_WNum_tag                         3
#define WInfoMO_WTime1_tag                       4
#define WInfoMO_WTime2_tag                       5
#define WInfoMO_WData1_tag                       6
#define WInfoMO_WData2_tag                       7
#define WInfoReqDTO_dtu_sn_tag                   1
#define WInfoReqDTO_time_tag                     2
#define WInfoReqDTO_package_count_tag            3
#define WInfoReqDTO_package_idx_tag              4
#define WInfoReqDTO_warn_device_tag              5
#define WInfoReqDTO_mWInfo_tag                   6
#define WInfoResDTO_time_ymd_hms_tag             1
#define WInfoResDTO_error_code_tag               2
#define WInfoResDTO_offset_tag                   3
#define WInfoResDTO_time_tag                     4
#define WWVDataReqDTO_dtu_sn_tag                 1
#define WWVDataReqDTO_time_tag                   2
#define WWVDataReqDTO_package_nub_tag            3
#define WWVDataReqDTO_package_now_tag            4
#define WWVDataReqDTO_pv_sn_tag                  5
#define WWVDataReqDTO_WCode_tag                  6
#define WWVDataReqDTO_WNum_tag                   7
#define WWVDataReqDTO_WTime1_tag                 8
#define WWVDataReqDTO_WVDataL_tag                9
#define WWVDataReqDTO_WPos_tag                   10
#define WWVDataReqDTO_mWVData_tag                11
#define WWVDataResDTO_time_ymd_hms_tag           1
#define WWVDataResDTO_package_now_tag            2
#define WWVDataResDTO_error_code_tag             3
#define WWVDataResDTO_offset_tag                 4
#define WWVDataResDTO_time_tag                   5

/* Struct field encoding specification for nanopb */
#define WInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    pv_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    WCode,             2) \
X(a, STATIC,   SINGULAR, INT32,    WNum,              3) \
X(a, STATIC,   SINGULAR, INT32,    WTime1,            4) \
X(a, STATIC,   SINGULAR, INT32,    WTime2,            5) \
X(a, STATIC,   SINGULAR, INT32,    WData1,            6) \
X(a, STATIC,   SINGULAR, INT32,    WData2,            7)
#define WInfoMO_CALLBACK NULL
#define WInfoMO_DEFAULT NULL

#define WInfoReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    package_count,     3) \
X(a, STATIC,   SINGULAR, INT32,    package_idx,       4) \
X(a, STATIC,   SINGULAR, INT32,    warn_device,       5) \
X(a, STATIC,   REPEATED, MESSAGE,  mWInfo,            6)
#define WInfoReqDTO_CALLBACK NULL
#define WInfoReqDTO_DEFAULT NULL
#define WInfoReqDTO_mWInfo_MSGTYPE WInfoMO

#define WInfoResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        2) \
X(a, STATIC,   SINGULAR, INT32,    offset,            3) \
X(a, STATIC,   SINGULAR, INT32,    time,              4)
#define WInfoResDTO_CALLBACK NULL
#define WInfoResDTO_DEFAULT NULL

#define WWVDataReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    package_nub,       3) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       4) \
X(a, STATIC,   SINGULAR, INT64,    pv_sn,             5) \
X(a, STATIC,   SINGULAR, INT32,    WCode,             6) \
X(a, STATIC,   SINGULAR, INT32,    WNum,              7) \
X(a, STATIC,   SINGULAR, INT32,    WTime1,            8) \
X(a, STATIC,   SINGULAR, INT32,    WVDataL,           9) \
X(a, STATIC,   SINGULAR, INT32,    WPos,             10) \
X(a, CALLBACK, SINGULAR, STRING,   mWVData,          11)
#define WWVDataReqDTO_CALLBACK pb_default_field_callback
#define WWVDataReqDTO_DEFAULT NULL

#define WWVDataResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       2) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        3) \
X(a, STATIC,   SINGULAR, INT32,    offset,            4) \
X(a, STATIC,   SINGULAR, INT32,    time,              5)
#define WWVDataResDTO_CALLBACK NULL
#define WWVDataResDTO_DEFAULT NULL

extern const pb_msgdesc_t WInfoMO_msg;
extern const pb_msgdesc_t WInfoReqDTO_msg;
extern const pb_msgdesc_t WInfoResDTO_msg;
extern const pb_msgdesc_t WWVDataReqDTO_msg;
extern const pb_msgdesc_t WWVDataResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WInfoMO_fields &WInfoMO_msg
#define WInfoReqDTO_fields &WInfoReqDTO_msg
#define WInfoResDTO_fields &WInfoResDTO_msg
#define WWVDataReqDTO_fields &WWVDataReqDTO_msg
#define WWVDataResDTO_fields &WWVDataResDTO_msg

/* Maximum encoded size of messages (where known) */
/* WWVDataReqDTO_size depends on runtime parameters */
#define ALARMDATA_PB_H_MAX_SIZE                  WInfoReqDTO_size
#define WInfoMO_size                             77
#define WInfoReqDTO_size                         2436
#define WInfoResDTO_size                         95
#define WWVDataResDTO_size                       106

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
