/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APPGETHISTPOWER_PB_H_INCLUDED
#define PB_APPGETHISTPOWER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AppGetHistPowerResDTO {
    int32_t control_point; /* Control point identifier */
    int32_t offset; /* Offset value */
    uint32_t requested_time; /* Time requested */
    uint32_t requested_day; /* Day requested */
} AppGetHistPowerResDTO;

typedef struct _AppGetHistPowerReqDTO {
    int64_t serial_number; /* Device serial number */
    int32_t access_point; /* Access point identifier */
    int32_t control_point; /* Control point identifier */
    int32_t offset; /* Offset value */
    uint32_t request_time; /* Timestamp of the request */
    uint32_t start_time; /* Start timestamp */
    uint32_t long_term_start; /* Long-term start timestamp */
    uint32_t absolute_start; /* Absolute start timestamp */
    uint32_t step_time; /* Step time */
    uint32_t relative_power; /* Relative power */
    uint32_t total_energy; /* Total energy */
    uint32_t daily_energy; /* Daily energy */
    pb_size_t power_array_count;
    int32_t power_array[100]; /* Array of power values */
    uint32_t warning_number; /* Warning number */
} AppGetHistPowerReqDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AppGetHistPowerResDTO_init_default       {0, 0, 0, 0}
#define AppGetHistPowerReqDTO_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define AppGetHistPowerResDTO_init_zero          {0, 0, 0, 0}
#define AppGetHistPowerReqDTO_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AppGetHistPowerResDTO_control_point_tag  1
#define AppGetHistPowerResDTO_offset_tag         2
#define AppGetHistPowerResDTO_requested_time_tag 3
#define AppGetHistPowerResDTO_requested_day_tag  4
#define AppGetHistPowerReqDTO_serial_number_tag  1
#define AppGetHistPowerReqDTO_access_point_tag   2
#define AppGetHistPowerReqDTO_control_point_tag  3
#define AppGetHistPowerReqDTO_offset_tag         4
#define AppGetHistPowerReqDTO_request_time_tag   5
#define AppGetHistPowerReqDTO_start_time_tag     6
#define AppGetHistPowerReqDTO_long_term_start_tag 7
#define AppGetHistPowerReqDTO_absolute_start_tag 8
#define AppGetHistPowerReqDTO_step_time_tag      9
#define AppGetHistPowerReqDTO_relative_power_tag 10
#define AppGetHistPowerReqDTO_total_energy_tag   11
#define AppGetHistPowerReqDTO_daily_energy_tag   12
#define AppGetHistPowerReqDTO_power_array_tag    13
#define AppGetHistPowerReqDTO_warning_number_tag 14

/* Struct field encoding specification for nanopb */
#define AppGetHistPowerResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    control_point,     1) \
X(a, STATIC,   SINGULAR, INT32,    offset,            2) \
X(a, STATIC,   SINGULAR, UINT32,   requested_time,    3) \
X(a, STATIC,   SINGULAR, UINT32,   requested_day,     4)
#define AppGetHistPowerResDTO_CALLBACK NULL
#define AppGetHistPowerResDTO_DEFAULT NULL

#define AppGetHistPowerReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    access_point,      2) \
X(a, STATIC,   SINGULAR, INT32,    control_point,     3) \
X(a, STATIC,   SINGULAR, INT32,    offset,            4) \
X(a, STATIC,   SINGULAR, UINT32,   request_time,      5) \
X(a, STATIC,   SINGULAR, UINT32,   start_time,        6) \
X(a, STATIC,   SINGULAR, UINT32,   long_term_start,   7) \
X(a, STATIC,   SINGULAR, UINT32,   absolute_start,    8) \
X(a, STATIC,   SINGULAR, UINT32,   step_time,         9) \
X(a, STATIC,   SINGULAR, UINT32,   relative_power,   10) \
X(a, STATIC,   SINGULAR, UINT32,   total_energy,     11) \
X(a, STATIC,   SINGULAR, UINT32,   daily_energy,     12) \
X(a, STATIC,   REPEATED, INT32,    power_array,      13) \
X(a, STATIC,   SINGULAR, UINT32,   warning_number,   14)
#define AppGetHistPowerReqDTO_CALLBACK NULL
#define AppGetHistPowerReqDTO_DEFAULT NULL

extern const pb_msgdesc_t AppGetHistPowerResDTO_msg;
extern const pb_msgdesc_t AppGetHistPowerReqDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppGetHistPowerResDTO_fields &AppGetHistPowerResDTO_msg
#define AppGetHistPowerReqDTO_fields &AppGetHistPowerReqDTO_msg

/* Maximum encoded size of messages (where known) */
#define APPGETHISTPOWER_PB_H_MAX_SIZE            AppGetHistPowerReqDTO_size
#define AppGetHistPowerReqDTO_size               1198
#define AppGetHistPowerResDTO_size               34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
