/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "APPInformationData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(APPDtuInfoMO, APPDtuInfoMO, AUTO)


PB_BIND(APPMeterInfoMO, APPMeterInfoMO, AUTO)


PB_BIND(APPRpInfoMO, APPRpInfoMO, AUTO)


PB_BIND(APPPvInfoMO, APPPvInfoMO, AUTO)


PB_BIND(APPFeatureMO, APPFeatureMO, AUTO)


PB_BIND(APPInfoDataReqDTO, APPInfoDataReqDTO, 2)


PB_BIND(APPInfoDataResDTO, APPInfoDataResDTO, AUTO)



