/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APPINFORMATIONDATA_PB_H_INCLUDED
#define PB_APPINFORMATIONDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _APPDtuInfoMO {
    int32_t device_kind;
    int32_t dtu_sw_version;
    int32_t dtu_hw_version;
    int32_t dtu_step_time;
    int32_t dtu_rf_hw;
    int32_t dtu_rf_sw;
    int32_t access_model;
    int32_t communication_time;
    int32_t signal_strength;
    char gprs_vsn[17];
    char wifi_version[17];
    char ka_nub[17];
    int32_t dtu_rule_id;
    int32_t dtu_error_code;
    int32_t dtu485_mode;
    int32_t dtu485_addr;
    int32_t sub1g_fqband;
    int32_t sub1g_chtnum;
    int32_t sub1g_chnum;
    int32_t sub1g_rp;
    int32_t sub1g_chtotal;
    char gprs_imei[33];
    int32_t dfs;
} APPDtuInfoMO;

typedef struct _APPMeterInfoMO {
    int32_t device_kind;
    int64_t meter_sn;
    int32_t meter_model;
    int32_t meter_ct;
    int32_t com_way;
    int32_t access_mode;
    int32_t sw_vsn;
    char meter_val[33];
} APPMeterInfoMO;

typedef struct _APPRpInfoMO {
    int32_t device_kind;
    int64_t rp_sn;
    int32_t rp_sw;
    int32_t rp_hw;
    int32_t rp_rule_id;
} APPRpInfoMO;

typedef struct _APPPvInfoMO {
    int32_t device_kind;
    int64_t pv_sn;
    int32_t pv_usfw;
    int32_t pv_sw_version;
    int32_t pv_hw_pn;
    int32_t pv_hw_version;
    int32_t pv_gpf_code;
    int32_t pv_gpf;
    int32_t pv_rf_hw;
    int32_t pv_rf_sw;
    int32_t mi_rule_id;
} APPPvInfoMO;

typedef struct _APPFeatureMO {
    int32_t key;
    char value[33];
} APPFeatureMO;

typedef struct _APPInfoDataReqDTO {
    char dtu_sn[17]; /* Serial number of the device */
    uint32_t time;
    int32_t device_nub;
    int32_t pv_nub;
    int32_t package_nub;
    int32_t package_now;
    int32_t channel;
    bool has_mAPPDtuInfo;
    APPDtuInfoMO mAPPDtuInfo;
    pb_size_t mAPPMeterInfo_count;
    APPMeterInfoMO mAPPMeterInfo[2];
    pb_size_t mAPPRpInfo_count;
    APPRpInfoMO mAPPRpInfo[2];
    pb_size_t mAPPpvInfo_count;
    APPPvInfoMO mAPPpvInfo[2];
    uint32_t mf;
    pb_size_t m_app_feature_count;
    APPFeatureMO m_app_feature[5];
} APPInfoDataReqDTO;

typedef struct _APPInfoDataResDTO {
    char ymd_hms[33];
    int32_t offset;
    int32_t package_now;
    int32_t err_code;
    uint32_t time;
} APPInfoDataResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define APPDtuInfoMO_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define APPMeterInfoMO_init_default              {0, 0, 0, 0, 0, 0, 0, ""}
#define APPRpInfoMO_init_default                 {0, 0, 0, 0, 0}
#define APPPvInfoMO_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define APPFeatureMO_init_default                {0, ""}
#define APPInfoDataReqDTO_init_default           {"", 0, 0, 0, 0, 0, 0, false, APPDtuInfoMO_init_default, 0, {APPMeterInfoMO_init_default, APPMeterInfoMO_init_default}, 0, {APPRpInfoMO_init_default, APPRpInfoMO_init_default}, 0, {APPPvInfoMO_init_default, APPPvInfoMO_init_default}, 0, 0, {APPFeatureMO_init_default, APPFeatureMO_init_default, APPFeatureMO_init_default, APPFeatureMO_init_default, APPFeatureMO_init_default}}
#define APPInfoDataResDTO_init_default           {"", 0, 0, 0, 0}
#define APPDtuInfoMO_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define APPMeterInfoMO_init_zero                 {0, 0, 0, 0, 0, 0, 0, ""}
#define APPRpInfoMO_init_zero                    {0, 0, 0, 0, 0}
#define APPPvInfoMO_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define APPFeatureMO_init_zero                   {0, ""}
#define APPInfoDataReqDTO_init_zero              {"", 0, 0, 0, 0, 0, 0, false, APPDtuInfoMO_init_zero, 0, {APPMeterInfoMO_init_zero, APPMeterInfoMO_init_zero}, 0, {APPRpInfoMO_init_zero, APPRpInfoMO_init_zero}, 0, {APPPvInfoMO_init_zero, APPPvInfoMO_init_zero}, 0, 0, {APPFeatureMO_init_zero, APPFeatureMO_init_zero, APPFeatureMO_init_zero, APPFeatureMO_init_zero, APPFeatureMO_init_zero}}
#define APPInfoDataResDTO_init_zero              {"", 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define APPDtuInfoMO_device_kind_tag             1
#define APPDtuInfoMO_dtu_sw_version_tag          2
#define APPDtuInfoMO_dtu_hw_version_tag          3
#define APPDtuInfoMO_dtu_step_time_tag           4
#define APPDtuInfoMO_dtu_rf_hw_tag               5
#define APPDtuInfoMO_dtu_rf_sw_tag               6
#define APPDtuInfoMO_access_model_tag            7
#define APPDtuInfoMO_communication_time_tag      8
#define APPDtuInfoMO_signal_strength_tag         9
#define APPDtuInfoMO_gprs_vsn_tag                10
#define APPDtuInfoMO_wifi_version_tag            11
#define APPDtuInfoMO_ka_nub_tag                  12
#define APPDtuInfoMO_dtu_rule_id_tag             13
#define APPDtuInfoMO_dtu_error_code_tag          14
#define APPDtuInfoMO_dtu485_mode_tag             15
#define APPDtuInfoMO_dtu485_addr_tag             16
#define APPDtuInfoMO_sub1g_fqband_tag            17
#define APPDtuInfoMO_sub1g_chtnum_tag            18
#define APPDtuInfoMO_sub1g_chnum_tag             19
#define APPDtuInfoMO_sub1g_rp_tag                20
#define APPDtuInfoMO_sub1g_chtotal_tag           21
#define APPDtuInfoMO_gprs_imei_tag               22
#define APPDtuInfoMO_dfs_tag                     23
#define APPMeterInfoMO_device_kind_tag           1
#define APPMeterInfoMO_meter_sn_tag              2
#define APPMeterInfoMO_meter_model_tag           3
#define APPMeterInfoMO_meter_ct_tag              4
#define APPMeterInfoMO_com_way_tag               5
#define APPMeterInfoMO_access_mode_tag           6
#define APPMeterInfoMO_sw_vsn_tag                7
#define APPMeterInfoMO_meter_val_tag             8
#define APPRpInfoMO_device_kind_tag              1
#define APPRpInfoMO_rp_sn_tag                    2
#define APPRpInfoMO_rp_sw_tag                    3
#define APPRpInfoMO_rp_hw_tag                    4
#define APPRpInfoMO_rp_rule_id_tag               5
#define APPPvInfoMO_device_kind_tag              1
#define APPPvInfoMO_pv_sn_tag                    2
#define APPPvInfoMO_pv_usfw_tag                  3
#define APPPvInfoMO_pv_sw_version_tag            4
#define APPPvInfoMO_pv_hw_pn_tag                 5
#define APPPvInfoMO_pv_hw_version_tag            6
#define APPPvInfoMO_pv_gpf_code_tag              7
#define APPPvInfoMO_pv_gpf_tag                   8
#define APPPvInfoMO_pv_rf_hw_tag                 9
#define APPPvInfoMO_pv_rf_sw_tag                 10
#define APPPvInfoMO_mi_rule_id_tag               11
#define APPFeatureMO_key_tag                     1
#define APPFeatureMO_value_tag                   2
#define APPInfoDataReqDTO_dtu_sn_tag             1
#define APPInfoDataReqDTO_time_tag               2
#define APPInfoDataReqDTO_device_nub_tag         3
#define APPInfoDataReqDTO_pv_nub_tag             4
#define APPInfoDataReqDTO_package_nub_tag        5
#define APPInfoDataReqDTO_package_now_tag        6
#define APPInfoDataReqDTO_channel_tag            7
#define APPInfoDataReqDTO_mAPPDtuInfo_tag        8
#define APPInfoDataReqDTO_mAPPMeterInfo_tag      9
#define APPInfoDataReqDTO_mAPPRpInfo_tag         10
#define APPInfoDataReqDTO_mAPPpvInfo_tag         11
#define APPInfoDataReqDTO_mf_tag                 12
#define APPInfoDataReqDTO_m_app_feature_tag      13
#define APPInfoDataResDTO_ymd_hms_tag            1
#define APPInfoDataResDTO_offset_tag             2
#define APPInfoDataResDTO_package_now_tag        3
#define APPInfoDataResDTO_err_code_tag           4
#define APPInfoDataResDTO_time_tag               5

/* Struct field encoding specification for nanopb */
#define APPDtuInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT32,    dtu_sw_version,    2) \
X(a, STATIC,   SINGULAR, INT32,    dtu_hw_version,    3) \
X(a, STATIC,   SINGULAR, INT32,    dtu_step_time,     4) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rf_hw,         5) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rf_sw,         6) \
X(a, STATIC,   SINGULAR, INT32,    access_model,      7) \
X(a, STATIC,   SINGULAR, INT32,    communication_time,   8) \
X(a, STATIC,   SINGULAR, INT32,    signal_strength,   9) \
X(a, STATIC,   SINGULAR, STRING,   gprs_vsn,         10) \
X(a, STATIC,   SINGULAR, STRING,   wifi_version,     11) \
X(a, STATIC,   SINGULAR, STRING,   ka_nub,           12) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rule_id,      13) \
X(a, STATIC,   SINGULAR, INT32,    dtu_error_code,   14) \
X(a, STATIC,   SINGULAR, INT32,    dtu485_mode,      15) \
X(a, STATIC,   SINGULAR, INT32,    dtu485_addr,      16) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_fqband,     17) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_chtnum,     18) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_chnum,      19) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_rp,         20) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_chtotal,    21) \
X(a, STATIC,   SINGULAR, STRING,   gprs_imei,        22) \
X(a, STATIC,   SINGULAR, INT32,    dfs,              23)
#define APPDtuInfoMO_CALLBACK NULL
#define APPDtuInfoMO_DEFAULT NULL

#define APPMeterInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    meter_sn,          2) \
X(a, STATIC,   SINGULAR, INT32,    meter_model,       3) \
X(a, STATIC,   SINGULAR, INT32,    meter_ct,          4) \
X(a, STATIC,   SINGULAR, INT32,    com_way,           5) \
X(a, STATIC,   SINGULAR, INT32,    access_mode,       6) \
X(a, STATIC,   SINGULAR, INT32,    sw_vsn,            7) \
X(a, STATIC,   SINGULAR, STRING,   meter_val,         8)
#define APPMeterInfoMO_CALLBACK NULL
#define APPMeterInfoMO_DEFAULT NULL

#define APPRpInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    rp_sn,             2) \
X(a, STATIC,   SINGULAR, INT32,    rp_sw,             3) \
X(a, STATIC,   SINGULAR, INT32,    rp_hw,             4) \
X(a, STATIC,   SINGULAR, INT32,    rp_rule_id,        5)
#define APPRpInfoMO_CALLBACK NULL
#define APPRpInfoMO_DEFAULT NULL

#define APPPvInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    pv_sn,             2) \
X(a, STATIC,   SINGULAR, INT32,    pv_usfw,           3) \
X(a, STATIC,   SINGULAR, INT32,    pv_sw_version,     4) \
X(a, STATIC,   SINGULAR, INT32,    pv_hw_pn,          5) \
X(a, STATIC,   SINGULAR, INT32,    pv_hw_version,     6) \
X(a, STATIC,   SINGULAR, INT32,    pv_gpf_code,       7) \
X(a, STATIC,   SINGULAR, INT32,    pv_gpf,            8) \
X(a, STATIC,   SINGULAR, INT32,    pv_rf_hw,          9) \
X(a, STATIC,   SINGULAR, INT32,    pv_rf_sw,         10) \
X(a, STATIC,   SINGULAR, INT32,    mi_rule_id,       11)
#define APPPvInfoMO_CALLBACK NULL
#define APPPvInfoMO_DEFAULT NULL

#define APPFeatureMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define APPFeatureMO_CALLBACK NULL
#define APPFeatureMO_DEFAULT NULL

#define APPInfoDataReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2) \
X(a, STATIC,   SINGULAR, INT32,    device_nub,        3) \
X(a, STATIC,   SINGULAR, INT32,    pv_nub,            4) \
X(a, STATIC,   SINGULAR, INT32,    package_nub,       5) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       6) \
X(a, STATIC,   SINGULAR, INT32,    channel,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mAPPDtuInfo,       8) \
X(a, STATIC,   REPEATED, MESSAGE,  mAPPMeterInfo,     9) \
X(a, STATIC,   REPEATED, MESSAGE,  mAPPRpInfo,       10) \
X(a, STATIC,   REPEATED, MESSAGE,  mAPPpvInfo,       11) \
X(a, STATIC,   SINGULAR, UINT32,   mf,               12) \
X(a, STATIC,   REPEATED, MESSAGE,  m_app_feature,    13)
#define APPInfoDataReqDTO_CALLBACK NULL
#define APPInfoDataReqDTO_DEFAULT NULL
#define APPInfoDataReqDTO_mAPPDtuInfo_MSGTYPE APPDtuInfoMO
#define APPInfoDataReqDTO_mAPPMeterInfo_MSGTYPE APPMeterInfoMO
#define APPInfoDataReqDTO_mAPPRpInfo_MSGTYPE APPRpInfoMO
#define APPInfoDataReqDTO_mAPPpvInfo_MSGTYPE APPPvInfoMO
#define APPInfoDataReqDTO_m_app_feature_MSGTYPE APPFeatureMO

#define APPInfoDataResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ymd_hms,           1) \
X(a, STATIC,   SINGULAR, INT32,    offset,            2) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       3) \
X(a, STATIC,   SINGULAR, INT32,    err_code,          4) \
X(a, STATIC,   SINGULAR, UINT32,   time,              5)
#define APPInfoDataResDTO_CALLBACK NULL
#define APPInfoDataResDTO_DEFAULT NULL

extern const pb_msgdesc_t APPDtuInfoMO_msg;
extern const pb_msgdesc_t APPMeterInfoMO_msg;
extern const pb_msgdesc_t APPRpInfoMO_msg;
extern const pb_msgdesc_t APPPvInfoMO_msg;
extern const pb_msgdesc_t APPFeatureMO_msg;
extern const pb_msgdesc_t APPInfoDataReqDTO_msg;
extern const pb_msgdesc_t APPInfoDataResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define APPDtuInfoMO_fields &APPDtuInfoMO_msg
#define APPMeterInfoMO_fields &APPMeterInfoMO_msg
#define APPRpInfoMO_fields &APPRpInfoMO_msg
#define APPPvInfoMO_fields &APPPvInfoMO_msg
#define APPFeatureMO_fields &APPFeatureMO_msg
#define APPInfoDataReqDTO_fields &APPInfoDataReqDTO_msg
#define APPInfoDataResDTO_fields &APPInfoDataResDTO_msg

/* Maximum encoded size of messages (where known) */
#define APPDtuInfoMO_size                        305
#define APPFeatureMO_size                        45
#define APPINFORMATIONDATA_PB_H_MAX_SIZE         APPInfoDataReqDTO_size
#define APPInfoDataReqDTO_size                   1214
#define APPInfoDataResDTO_size                   73
#define APPMeterInfoMO_size                      111
#define APPPvInfoMO_size                         121
#define APPRpInfoMO_size                         55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
