/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "CommandPB.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommandResDTO, CommandResDTO, AUTO)


PB_BIND(CommandReqDTO, CommandReqDTO, AUTO)


PB_BIND(ESOperatingStatusMO, ESOperatingStatusMO, AUTO)


PB_BIND(MIOperatingStatusMO, MIOperatingStatusMO, AUTO)


PB_BIND(MIErrorStatusMO, MIErrorStatusMO, AUTO)


PB_BIND(ESSucStatusMO, ESSucStatusMO, AUTO)


PB_BIND(ESErrorStatusMO, ESErrorStatusMO, AUTO)


PB_BIND(CommandStatusReqDTO, CommandStatusReqDTO, 2)


PB_BIND(CommandStatusResDTO, CommandStatusResDTO, AUTO)



