/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GETCONFIG_PB_H_INCLUDED
#define PB_GETCONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GetConfigResDTO {
    int32_t offset; /* Offset in the response */
    uint32_t time; /* Timestamp of the response */
} GetConfigResDTO;

typedef struct _GetConfigReqDTO {
    int32_t request_offset; /* Offset in the request */
    uint32_t request_time; /* Timestamp of the request */
    int32_t lock_password; /* Lock password */
    int32_t lock_time; /* Lock time */
    int32_t limit_power_mypower; /* Limit power mypower */
    int32_t zero_export_433_addr; /* Zero export 433 address */
    int32_t zero_export_enable; /* Zero export enable */
    int32_t netmode_select; /* Netmode select */
    int32_t channel_select; /* Channel select */
    int32_t server_send_time; /* Server send time */
    int32_t wifi_rssi; /* Wifi RSSI */
    int32_t serverport; /* Server port */
    pb_callback_t apn_set; /* Access Point Name (APN) set */
    pb_callback_t meter_kind; /* Meter kind */
    pb_callback_t meter_interface; /* Meter interface */
    char wifi_ssid[129]; /* Wifi SSID */
    char wifi_password[129]; /* Wifi password */
    pb_callback_t server_domain_name; /* Server domain name */
    int32_t inv_type; /* Inverter type */
    char dtu_sn[17]; /* DTU serial number */
    int32_t access_model; /* Access model */
    int32_t mac_0; /* MAC address byte 0 */
    int32_t mac_1; /* MAC address byte 1 */
    int32_t mac_2; /* MAC address byte 2 */
    int32_t mac_3; /* MAC address byte 3 */
    int32_t dhcp_switch; /* DHCP switch */
    int32_t ip_addr_0; /* IP address byte 0 */
    int32_t ip_addr_1; /* IP address byte 1 */
    int32_t ip_addr_2; /* IP address byte 2 */
    int32_t ip_addr_3; /* IP address byte 3 */
    int32_t subnet_mask_0; /* Subnet mask byte 0 */
    int32_t subnet_mask_1; /* Subnet mask byte 1 */
    int32_t subnet_mask_2; /* Subnet mask byte 2 */
    int32_t subnet_mask_3; /* Subnet mask byte 3 */
    int32_t default_gateway_0; /* Default gateway byte 0 */
    int32_t default_gateway_1; /* Default gateway byte 1 */
    int32_t default_gateway_2; /* Default gateway byte 2 */
    int32_t default_gateway_3; /* Default gateway byte 3 */
    pb_callback_t ka_nub; /* KA number */
    char apn_name[65]; /* APN name */
    char apn_password[65]; /* APN password */
    int32_t sub1g_sweep_switch; /* Sub1G sweep switch */
    int32_t sub1g_work_channel; /* Sub1G work channel */
    int32_t cable_dns_0; /* Cable DNS byte 0 */
    int32_t cable_dns_1; /* Cable DNS byte 1 */
    int32_t cable_dns_2; /* Cable DNS byte 2 */
    int32_t cable_dns_3; /* Cable DNS byte 3 */
    int32_t wifi_ip_addr_0; /* Wifi IP address byte 0 */
    int32_t wifi_ip_addr_1; /* Wifi IP address byte 1 */
    int32_t wifi_ip_addr_2; /* Wifi IP address byte 2 */
    int32_t wifi_ip_addr_3; /* Wifi IP address byte 3 */
    int32_t mac_4; /* MAC address byte 4 */
    int32_t mac_5; /* MAC address byte 5 */
    int32_t wifi_mac_0; /* Wifi MAC address byte 0 */
    int32_t wifi_mac_1; /* Wifi MAC address byte 1 */
    int32_t wifi_mac_2; /* Wifi MAC address byte 2 */
    int32_t wifi_mac_3; /* Wifi MAC address byte 3 */
    int32_t wifi_mac_4; /* Wifi MAC address byte 4 */
    int32_t wifi_mac_5; /* Wifi MAC address byte 5 */
    pb_callback_t gprs_imei; /* GPRS IMEI */
    char dtu_ap_ssid[65]; /* DTU Access Point (AP) SSID */
    char dtu_ap_pass[65]; /* DTU AP password */
} GetConfigReqDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GetConfigResDTO_init_default             {0, 0}
#define GetConfigReqDTO_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, "", "", {{NULL}, NULL}, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, "", ""}
#define GetConfigResDTO_init_zero                {0, 0}
#define GetConfigReqDTO_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, "", "", {{NULL}, NULL}, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define GetConfigResDTO_offset_tag               1
#define GetConfigResDTO_time_tag                 2
#define GetConfigReqDTO_request_offset_tag       1
#define GetConfigReqDTO_request_time_tag         2
#define GetConfigReqDTO_lock_password_tag        3
#define GetConfigReqDTO_lock_time_tag            4
#define GetConfigReqDTO_limit_power_mypower_tag  5
#define GetConfigReqDTO_zero_export_433_addr_tag 6
#define GetConfigReqDTO_zero_export_enable_tag   7
#define GetConfigReqDTO_netmode_select_tag       8
#define GetConfigReqDTO_channel_select_tag       9
#define GetConfigReqDTO_server_send_time_tag     10
#define GetConfigReqDTO_wifi_rssi_tag            11
#define GetConfigReqDTO_serverport_tag           12
#define GetConfigReqDTO_apn_set_tag              13
#define GetConfigReqDTO_meter_kind_tag           14
#define GetConfigReqDTO_meter_interface_tag      15
#define GetConfigReqDTO_wifi_ssid_tag            16
#define GetConfigReqDTO_wifi_password_tag        17
#define GetConfigReqDTO_server_domain_name_tag   18
#define GetConfigReqDTO_inv_type_tag             19
#define GetConfigReqDTO_dtu_sn_tag               20
#define GetConfigReqDTO_access_model_tag         21
#define GetConfigReqDTO_mac_0_tag                22
#define GetConfigReqDTO_mac_1_tag                23
#define GetConfigReqDTO_mac_2_tag                24
#define GetConfigReqDTO_mac_3_tag                25
#define GetConfigReqDTO_dhcp_switch_tag          26
#define GetConfigReqDTO_ip_addr_0_tag            27
#define GetConfigReqDTO_ip_addr_1_tag            28
#define GetConfigReqDTO_ip_addr_2_tag            29
#define GetConfigReqDTO_ip_addr_3_tag            30
#define GetConfigReqDTO_subnet_mask_0_tag        31
#define GetConfigReqDTO_subnet_mask_1_tag        32
#define GetConfigReqDTO_subnet_mask_2_tag        33
#define GetConfigReqDTO_subnet_mask_3_tag        34
#define GetConfigReqDTO_default_gateway_0_tag    35
#define GetConfigReqDTO_default_gateway_1_tag    36
#define GetConfigReqDTO_default_gateway_2_tag    37
#define GetConfigReqDTO_default_gateway_3_tag    38
#define GetConfigReqDTO_ka_nub_tag               39
#define GetConfigReqDTO_apn_name_tag             40
#define GetConfigReqDTO_apn_password_tag         41
#define GetConfigReqDTO_sub1g_sweep_switch_tag   42
#define GetConfigReqDTO_sub1g_work_channel_tag   43
#define GetConfigReqDTO_cable_dns_0_tag          44
#define GetConfigReqDTO_cable_dns_1_tag          45
#define GetConfigReqDTO_cable_dns_2_tag          46
#define GetConfigReqDTO_cable_dns_3_tag          47
#define GetConfigReqDTO_wifi_ip_addr_0_tag       48
#define GetConfigReqDTO_wifi_ip_addr_1_tag       49
#define GetConfigReqDTO_wifi_ip_addr_2_tag       50
#define GetConfigReqDTO_wifi_ip_addr_3_tag       51
#define GetConfigReqDTO_mac_4_tag                52
#define GetConfigReqDTO_mac_5_tag                53
#define GetConfigReqDTO_wifi_mac_0_tag           54
#define GetConfigReqDTO_wifi_mac_1_tag           55
#define GetConfigReqDTO_wifi_mac_2_tag           56
#define GetConfigReqDTO_wifi_mac_3_tag           57
#define GetConfigReqDTO_wifi_mac_4_tag           58
#define GetConfigReqDTO_wifi_mac_5_tag           59
#define GetConfigReqDTO_gprs_imei_tag            60
#define GetConfigReqDTO_dtu_ap_ssid_tag          61
#define GetConfigReqDTO_dtu_ap_pass_tag          62

/* Struct field encoding specification for nanopb */
#define GetConfigResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2)
#define GetConfigResDTO_CALLBACK NULL
#define GetConfigResDTO_DEFAULT NULL

#define GetConfigReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    request_offset,    1) \
X(a, STATIC,   SINGULAR, UINT32,   request_time,      2) \
X(a, STATIC,   SINGULAR, INT32,    lock_password,     3) \
X(a, STATIC,   SINGULAR, INT32,    lock_time,         4) \
X(a, STATIC,   SINGULAR, INT32,    limit_power_mypower,   5) \
X(a, STATIC,   SINGULAR, INT32,    zero_export_433_addr,   6) \
X(a, STATIC,   SINGULAR, INT32,    zero_export_enable,   7) \
X(a, STATIC,   SINGULAR, INT32,    netmode_select,    8) \
X(a, STATIC,   SINGULAR, INT32,    channel_select,    9) \
X(a, STATIC,   SINGULAR, INT32,    server_send_time,  10) \
X(a, STATIC,   SINGULAR, INT32,    wifi_rssi,        11) \
X(a, STATIC,   SINGULAR, INT32,    serverport,       12) \
X(a, CALLBACK, SINGULAR, STRING,   apn_set,          13) \
X(a, CALLBACK, SINGULAR, STRING,   meter_kind,       14) \
X(a, CALLBACK, SINGULAR, STRING,   meter_interface,  15) \
X(a, STATIC,   SINGULAR, STRING,   wifi_ssid,        16) \
X(a, STATIC,   SINGULAR, STRING,   wifi_password,    17) \
X(a, CALLBACK, SINGULAR, STRING,   server_domain_name,  18) \
X(a, STATIC,   SINGULAR, INT32,    inv_type,         19) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,           20) \
X(a, STATIC,   SINGULAR, INT32,    access_model,     21) \
X(a, STATIC,   SINGULAR, INT32,    mac_0,            22) \
X(a, STATIC,   SINGULAR, INT32,    mac_1,            23) \
X(a, STATIC,   SINGULAR, INT32,    mac_2,            24) \
X(a, STATIC,   SINGULAR, INT32,    mac_3,            25) \
X(a, STATIC,   SINGULAR, INT32,    dhcp_switch,      26) \
X(a, STATIC,   SINGULAR, INT32,    ip_addr_0,        27) \
X(a, STATIC,   SINGULAR, INT32,    ip_addr_1,        28) \
X(a, STATIC,   SINGULAR, INT32,    ip_addr_2,        29) \
X(a, STATIC,   SINGULAR, INT32,    ip_addr_3,        30) \
X(a, STATIC,   SINGULAR, INT32,    subnet_mask_0,    31) \
X(a, STATIC,   SINGULAR, INT32,    subnet_mask_1,    32) \
X(a, STATIC,   SINGULAR, INT32,    subnet_mask_2,    33) \
X(a, STATIC,   SINGULAR, INT32,    subnet_mask_3,    34) \
X(a, STATIC,   SINGULAR, INT32,    default_gateway_0,  35) \
X(a, STATIC,   SINGULAR, INT32,    default_gateway_1,  36) \
X(a, STATIC,   SINGULAR, INT32,    default_gateway_2,  37) \
X(a, STATIC,   SINGULAR, INT32,    default_gateway_3,  38) \
X(a, CALLBACK, SINGULAR, STRING,   ka_nub,           39) \
X(a, STATIC,   SINGULAR, STRING,   apn_name,         40) \
X(a, STATIC,   SINGULAR, STRING,   apn_password,     41) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_sweep_switch,  42) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_work_channel,  43) \
X(a, STATIC,   SINGULAR, INT32,    cable_dns_0,      44) \
X(a, STATIC,   SINGULAR, INT32,    cable_dns_1,      45) \
X(a, STATIC,   SINGULAR, INT32,    cable_dns_2,      46) \
X(a, STATIC,   SINGULAR, INT32,    cable_dns_3,      47) \
X(a, STATIC,   SINGULAR, INT32,    wifi_ip_addr_0,   48) \
X(a, STATIC,   SINGULAR, INT32,    wifi_ip_addr_1,   49) \
X(a, STATIC,   SINGULAR, INT32,    wifi_ip_addr_2,   50) \
X(a, STATIC,   SINGULAR, INT32,    wifi_ip_addr_3,   51) \
X(a, STATIC,   SINGULAR, INT32,    mac_4,            52) \
X(a, STATIC,   SINGULAR, INT32,    mac_5,            53) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_0,       54) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_1,       55) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_2,       56) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_3,       57) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_4,       58) \
X(a, STATIC,   SINGULAR, INT32,    wifi_mac_5,       59) \
X(a, CALLBACK, SINGULAR, STRING,   gprs_imei,        60) \
X(a, STATIC,   SINGULAR, STRING,   dtu_ap_ssid,      61) \
X(a, STATIC,   SINGULAR, STRING,   dtu_ap_pass,      62)
#define GetConfigReqDTO_CALLBACK pb_default_field_callback
#define GetConfigReqDTO_DEFAULT NULL

extern const pb_msgdesc_t GetConfigResDTO_msg;
extern const pb_msgdesc_t GetConfigReqDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GetConfigResDTO_fields &GetConfigResDTO_msg
#define GetConfigReqDTO_fields &GetConfigReqDTO_msg

/* Maximum encoded size of messages (where known) */
/* GetConfigReqDTO_size depends on runtime parameters */
#define GETCONFIG_PB_H_MAX_SIZE                  GetConfigResDTO_size
#define GetConfigResDTO_size                     17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
