/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_REALTIMEDATANEW_PB_H_INCLUDED
#define PB_REALTIMEDATANEW_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MeterMO {
    int32_t device_type; /* Device type identifier */
    int64_t serial_number; /* Serial number of the meter */
    int32_t phase_total_power; /* Total power across all phases (Watts) */
    int32_t phase_A_power; /* Power in phase A (Watts) */
    int32_t phase_B_power; /* Power in phase B (Watts) */
    int32_t phase_C_power; /* Power in phase C (Watts) */
    int32_t power_factor_total; /* Total power factor */
    int32_t energy_total_power; /* Total energy generated (Watt-hours) */
    int32_t energy_phase_A; /* Energy generated in phase A (Watt-hours) */
    int32_t energy_phase_B; /* Energy generated in phase B (Watt-hours) */
    int32_t energy_phase_C; /* Energy generated in phase C (Watt-hours) */
    int32_t energy_total_consumed; /* Total energy consumed (Watt-hours) */
    int32_t energy_phase_A_consumed; /* Energy consumed in phase A (Watt-hours) */
    int32_t energy_phase_B_consumed; /* Energy consumed in phase B (Watt-hours) */
    int32_t energy_phase_C_consumed; /* Energy consumed in phase C (Watt-hours) */
    int32_t fault_code; /* Fault code indicator */
    int32_t voltage_phase_A; /* Voltage in phase A (Volts) */
    int32_t voltage_phase_B; /* Voltage in phase B (Volts) */
    int32_t voltage_phase_C; /* Voltage in phase C (Volts) */
    int32_t current_phase_A; /* Current in phase A (Amperes) */
    int32_t current_phase_B; /* Current in phase B (Amperes) */
    int32_t current_phase_C; /* Current in phase C (Amperes) */
    int32_t power_factor_phase_A; /* Power factor in phase A */
    int32_t power_factor_phase_B; /* Power factor in phase B */
    int32_t power_factor_phase_C; /* Power factor in phase C */
} MeterMO;

typedef struct _RpMO {
    int64_t serial_number; /* Serial number of the device */
    int32_t signature; /* Signature value */
    int32_t channel; /* Channel number */
    int32_t pv_number; /* Photovoltaic (PV) number */
    int32_t link_status; /* Link status indicator */
} RpMO;

typedef struct _RSDMO {
    int64_t serial_number; /* Serial number of the device */
    int32_t firmware_version; /* Firmware version */
    int32_t voltage; /* Voltage value */
    int32_t power; /* Power value */
    int32_t temperature; /* Temperature value */
    int32_t warning_number; /* Warning number */
    int32_t crc_checksum; /* CRC checksum */
    int32_t link_status; /* Link status indicator */
} RSDMO;

typedef struct _SGSMO {
    int64_t serial_number; /* Serial number of the device */
    int32_t firmware_version; /* Firmware version */
    int32_t voltage; /* Grid voltage (Volts) */
    int32_t frequency; /* Grid frequency (Hertz) */
    int32_t active_power; /* Active power (Watts) */
    int32_t reactive_power; /* Reactive power (VAR) */
    int32_t current; /* Current (Amperes) */
    int32_t power_factor; /* Power factor */
    int32_t temperature; /* Temperature value */
    int32_t warning_number; /* Warning number */
    int32_t crc_checksum; /* CRC checksum */
    int32_t link_status; /* Link status indicator */
    int32_t power_limit; /* Power limit (Watts) */
    int32_t modulation_index_signal; /* Modulation index signal */
} SGSMO;

typedef struct _TGSMO {
    int64_t serial_number; /* Serial number of the device */
    int32_t firmware_version; /* Firmware version */
    int32_t voltage_phase_A; /* Voltage in phase A (Volts) */
    int32_t voltage_phase_B; /* Voltage in phase B (Volts) */
    int32_t voltage_phase_C; /* Voltage in phase C (Volts) */
    int32_t voltage_line_AB; /* Voltage between lines A and B (Volts) */
    int32_t voltage_line_BC; /* Voltage between lines B and C (Volts) */
    int32_t voltage_line_CA; /* Voltage between lines C and A (Volts) */
    int32_t frequency; /* Frequency (Hertz) */
    int32_t active_power; /* Active power (Watts) */
    int32_t reactive_power; /* Reactive power (VAR) */
    int32_t current_phase_A; /* Current in phase A (Amperes) */
    int32_t current_phase_B; /* Current in phase B (Amperes) */
    int32_t current_phase_C; /* Current in phase C (Amperes) */
    int32_t power_factor; /* Power factor */
    int32_t temperature; /* Temperature value */
    int32_t warning_number; /* Warning number */
    int32_t crc_checksum; /* CRC checksum */
    int32_t link_status; /* Link status indicator */
    int32_t modulation_index_signal; /* Modulation index signal */
} TGSMO;

typedef struct _PvMO {
    int64_t serial_number; /* Serial number of the device */
    int32_t port_number; /* Port number */
    int32_t voltage; /* Voltage (Volts) */
    int32_t current; /* Current (Amperes) */
    int32_t power; /* Power (Watts) */
    int32_t energy_total; /* Total energy generated (Watt-hours) */
    int32_t energy_daily; /* Daily energy generated (Watt-hours) */
    int32_t error_code; /* Error code indicator */
} PvMO;

typedef struct _RealDataNewReqDTO {
    char device_serial_number[17]; /* Serial number of the device */
    int32_t timestamp; /* Timestamp of the data */
    int32_t ap; /* Number of packages */
    int32_t cp; /* Current package */
    int32_t firmware_version; /* Firmware version */
    pb_callback_t meter_data; /* Meter data array */
    pb_callback_t rp_data; /* RpMO data array */
    pb_callback_t rsd_data; /* RSDMO data array */
    pb_size_t sgs_data_count;
    SGSMO sgs_data[2]; /* SGSMO data array */
    pb_callback_t tgs_data; /* TGSMO data array */
    pb_size_t pv_data_count;
    PvMO pv_data[4]; /* PvMO data array */
    uint64_t dtu_power; /* Power of the DTU (Watts) */
    uint64_t dtu_daily_energy; /* Daily energy of the DTU (Watt-hours) */
} RealDataNewReqDTO;

typedef struct _RealDataNewResDTO {
    pb_callback_t time_ymd_hms; /* Timestamp in the format YMD_HMS */
    int32_t cp; /* Current Package */
    int32_t error_code; /* Error code indicator */
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp value */
} RealDataNewResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MeterMO_init_default                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RpMO_init_default                        {0, 0, 0, 0, 0}
#define RSDMO_init_default                       {0, 0, 0, 0, 0, 0, 0, 0}
#define SGSMO_init_default                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TGSMO_init_default                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PvMO_init_default                        {0, 0, 0, 0, 0, 0, 0, 0}
#define RealDataNewReqDTO_init_default           {"", 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {SGSMO_init_default, SGSMO_init_default}, {{NULL}, NULL}, 0, {PvMO_init_default, PvMO_init_default, PvMO_init_default, PvMO_init_default}, 0, 0}
#define RealDataNewResDTO_init_default           {{{NULL}, NULL}, 0, 0, 0, 0}
#define MeterMO_init_zero                        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RpMO_init_zero                           {0, 0, 0, 0, 0}
#define RSDMO_init_zero                          {0, 0, 0, 0, 0, 0, 0, 0}
#define SGSMO_init_zero                          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TGSMO_init_zero                          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PvMO_init_zero                           {0, 0, 0, 0, 0, 0, 0, 0}
#define RealDataNewReqDTO_init_zero              {"", 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {SGSMO_init_zero, SGSMO_init_zero}, {{NULL}, NULL}, 0, {PvMO_init_zero, PvMO_init_zero, PvMO_init_zero, PvMO_init_zero}, 0, 0}
#define RealDataNewResDTO_init_zero              {{{NULL}, NULL}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MeterMO_device_type_tag                  1
#define MeterMO_serial_number_tag                2
#define MeterMO_phase_total_power_tag            3
#define MeterMO_phase_A_power_tag                4
#define MeterMO_phase_B_power_tag                5
#define MeterMO_phase_C_power_tag                6
#define MeterMO_power_factor_total_tag           7
#define MeterMO_energy_total_power_tag           8
#define MeterMO_energy_phase_A_tag               9
#define MeterMO_energy_phase_B_tag               10
#define MeterMO_energy_phase_C_tag               11
#define MeterMO_energy_total_consumed_tag        12
#define MeterMO_energy_phase_A_consumed_tag      13
#define MeterMO_energy_phase_B_consumed_tag      14
#define MeterMO_energy_phase_C_consumed_tag      15
#define MeterMO_fault_code_tag                   16
#define MeterMO_voltage_phase_A_tag              17
#define MeterMO_voltage_phase_B_tag              18
#define MeterMO_voltage_phase_C_tag              19
#define MeterMO_current_phase_A_tag              20
#define MeterMO_current_phase_B_tag              21
#define MeterMO_current_phase_C_tag              22
#define MeterMO_power_factor_phase_A_tag         23
#define MeterMO_power_factor_phase_B_tag         24
#define MeterMO_power_factor_phase_C_tag         25
#define RpMO_serial_number_tag                   1
#define RpMO_signature_tag                       2
#define RpMO_channel_tag                         3
#define RpMO_pv_number_tag                       4
#define RpMO_link_status_tag                     5
#define RSDMO_serial_number_tag                  1
#define RSDMO_firmware_version_tag               2
#define RSDMO_voltage_tag                        3
#define RSDMO_power_tag                          4
#define RSDMO_temperature_tag                    5
#define RSDMO_warning_number_tag                 6
#define RSDMO_crc_checksum_tag                   7
#define RSDMO_link_status_tag                    8
#define SGSMO_serial_number_tag                  1
#define SGSMO_firmware_version_tag               2
#define SGSMO_voltage_tag                        3
#define SGSMO_frequency_tag                      4
#define SGSMO_active_power_tag                   5
#define SGSMO_reactive_power_tag                 6
#define SGSMO_current_tag                        7
#define SGSMO_power_factor_tag                   8
#define SGSMO_temperature_tag                    9
#define SGSMO_warning_number_tag                 10
#define SGSMO_crc_checksum_tag                   11
#define SGSMO_link_status_tag                    12
#define SGSMO_power_limit_tag                    13
#define SGSMO_modulation_index_signal_tag        20
#define TGSMO_serial_number_tag                  1
#define TGSMO_firmware_version_tag               2
#define TGSMO_voltage_phase_A_tag                3
#define TGSMO_voltage_phase_B_tag                4
#define TGSMO_voltage_phase_C_tag                5
#define TGSMO_voltage_line_AB_tag                6
#define TGSMO_voltage_line_BC_tag                7
#define TGSMO_voltage_line_CA_tag                8
#define TGSMO_frequency_tag                      9
#define TGSMO_active_power_tag                   10
#define TGSMO_reactive_power_tag                 11
#define TGSMO_current_phase_A_tag                12
#define TGSMO_current_phase_B_tag                13
#define TGSMO_current_phase_C_tag                14
#define TGSMO_power_factor_tag                   15
#define TGSMO_temperature_tag                    16
#define TGSMO_warning_number_tag                 17
#define TGSMO_crc_checksum_tag                   18
#define TGSMO_link_status_tag                    19
#define TGSMO_modulation_index_signal_tag        20
#define PvMO_serial_number_tag                   1
#define PvMO_port_number_tag                     2
#define PvMO_voltage_tag                         3
#define PvMO_current_tag                         4
#define PvMO_power_tag                           5
#define PvMO_energy_total_tag                    6
#define PvMO_energy_daily_tag                    7
#define PvMO_error_code_tag                      8
#define RealDataNewReqDTO_device_serial_number_tag 1
#define RealDataNewReqDTO_timestamp_tag          2
#define RealDataNewReqDTO_ap_tag                 3
#define RealDataNewReqDTO_cp_tag                 4
#define RealDataNewReqDTO_firmware_version_tag   5
#define RealDataNewReqDTO_meter_data_tag         6
#define RealDataNewReqDTO_rp_data_tag            7
#define RealDataNewReqDTO_rsd_data_tag           8
#define RealDataNewReqDTO_sgs_data_tag           9
#define RealDataNewReqDTO_tgs_data_tag           10
#define RealDataNewReqDTO_pv_data_tag            11
#define RealDataNewReqDTO_dtu_power_tag          12
#define RealDataNewReqDTO_dtu_daily_energy_tag   13
#define RealDataNewResDTO_time_ymd_hms_tag       1
#define RealDataNewResDTO_cp_tag                 2
#define RealDataNewResDTO_error_code_tag         3
#define RealDataNewResDTO_offset_tag             4
#define RealDataNewResDTO_time_tag               5

/* Struct field encoding specification for nanopb */
#define MeterMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_type,       1) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     2) \
X(a, STATIC,   SINGULAR, INT32,    phase_total_power,   3) \
X(a, STATIC,   SINGULAR, INT32,    phase_A_power,     4) \
X(a, STATIC,   SINGULAR, INT32,    phase_B_power,     5) \
X(a, STATIC,   SINGULAR, INT32,    phase_C_power,     6) \
X(a, STATIC,   SINGULAR, INT32,    power_factor_total,   7) \
X(a, STATIC,   SINGULAR, INT32,    energy_total_power,   8) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_A,    9) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_B,   10) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_C,   11) \
X(a, STATIC,   SINGULAR, INT32,    energy_total_consumed,  12) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_A_consumed,  13) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_B_consumed,  14) \
X(a, STATIC,   SINGULAR, INT32,    energy_phase_C_consumed,  15) \
X(a, STATIC,   SINGULAR, INT32,    fault_code,       16) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_A,  17) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_B,  18) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_C,  19) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_A,  20) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_B,  21) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_C,  22) \
X(a, STATIC,   SINGULAR, INT32,    power_factor_phase_A,  23) \
X(a, STATIC,   SINGULAR, INT32,    power_factor_phase_B,  24) \
X(a, STATIC,   SINGULAR, INT32,    power_factor_phase_C,  25)
#define MeterMO_CALLBACK NULL
#define MeterMO_DEFAULT NULL

#define RpMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    signature,         2) \
X(a, STATIC,   SINGULAR, INT32,    channel,           3) \
X(a, STATIC,   SINGULAR, INT32,    pv_number,         4) \
X(a, STATIC,   SINGULAR, INT32,    link_status,       5)
#define RpMO_CALLBACK NULL
#define RpMO_DEFAULT NULL

#define RSDMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    firmware_version,   2) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           3) \
X(a, STATIC,   SINGULAR, INT32,    power,             4) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       5) \
X(a, STATIC,   SINGULAR, INT32,    warning_number,    6) \
X(a, STATIC,   SINGULAR, INT32,    crc_checksum,      7) \
X(a, STATIC,   SINGULAR, INT32,    link_status,       8)
#define RSDMO_CALLBACK NULL
#define RSDMO_DEFAULT NULL

#define SGSMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    firmware_version,   2) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           3) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         4) \
X(a, STATIC,   SINGULAR, INT32,    active_power,      5) \
X(a, STATIC,   SINGULAR, INT32,    reactive_power,    6) \
X(a, STATIC,   SINGULAR, INT32,    current,           7) \
X(a, STATIC,   SINGULAR, INT32,    power_factor,      8) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       9) \
X(a, STATIC,   SINGULAR, INT32,    warning_number,   10) \
X(a, STATIC,   SINGULAR, INT32,    crc_checksum,     11) \
X(a, STATIC,   SINGULAR, INT32,    link_status,      12) \
X(a, STATIC,   SINGULAR, INT32,    power_limit,      13) \
X(a, STATIC,   SINGULAR, INT32,    modulation_index_signal,  20)
#define SGSMO_CALLBACK NULL
#define SGSMO_DEFAULT NULL

#define TGSMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    firmware_version,   2) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_A,   3) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_B,   4) \
X(a, STATIC,   SINGULAR, INT32,    voltage_phase_C,   5) \
X(a, STATIC,   SINGULAR, INT32,    voltage_line_AB,   6) \
X(a, STATIC,   SINGULAR, INT32,    voltage_line_BC,   7) \
X(a, STATIC,   SINGULAR, INT32,    voltage_line_CA,   8) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         9) \
X(a, STATIC,   SINGULAR, INT32,    active_power,     10) \
X(a, STATIC,   SINGULAR, INT32,    reactive_power,   11) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_A,  12) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_B,  13) \
X(a, STATIC,   SINGULAR, INT32,    current_phase_C,  14) \
X(a, STATIC,   SINGULAR, INT32,    power_factor,     15) \
X(a, STATIC,   SINGULAR, INT32,    temperature,      16) \
X(a, STATIC,   SINGULAR, INT32,    warning_number,   17) \
X(a, STATIC,   SINGULAR, INT32,    crc_checksum,     18) \
X(a, STATIC,   SINGULAR, INT32,    link_status,      19) \
X(a, STATIC,   SINGULAR, INT32,    modulation_index_signal,  20)
#define TGSMO_CALLBACK NULL
#define TGSMO_DEFAULT NULL

#define PvMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    serial_number,     1) \
X(a, STATIC,   SINGULAR, INT32,    port_number,       2) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           3) \
X(a, STATIC,   SINGULAR, INT32,    current,           4) \
X(a, STATIC,   SINGULAR, INT32,    power,             5) \
X(a, STATIC,   SINGULAR, INT32,    energy_total,      6) \
X(a, STATIC,   SINGULAR, INT32,    energy_daily,      7) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        8)
#define PvMO_CALLBACK NULL
#define PvMO_DEFAULT NULL

#define RealDataNewReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_serial_number,   1) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    ap,                3) \
X(a, STATIC,   SINGULAR, INT32,    cp,                4) \
X(a, STATIC,   SINGULAR, INT32,    firmware_version,   5) \
X(a, CALLBACK, REPEATED, MESSAGE,  meter_data,        6) \
X(a, CALLBACK, REPEATED, MESSAGE,  rp_data,           7) \
X(a, CALLBACK, REPEATED, MESSAGE,  rsd_data,          8) \
X(a, STATIC,   REPEATED, MESSAGE,  sgs_data,          9) \
X(a, CALLBACK, REPEATED, MESSAGE,  tgs_data,         10) \
X(a, STATIC,   REPEATED, MESSAGE,  pv_data,          11) \
X(a, STATIC,   SINGULAR, UINT64,   dtu_power,        12) \
X(a, STATIC,   SINGULAR, UINT64,   dtu_daily_energy,  13)
#define RealDataNewReqDTO_CALLBACK pb_default_field_callback
#define RealDataNewReqDTO_DEFAULT NULL
#define RealDataNewReqDTO_meter_data_MSGTYPE MeterMO
#define RealDataNewReqDTO_rp_data_MSGTYPE RpMO
#define RealDataNewReqDTO_rsd_data_MSGTYPE RSDMO
#define RealDataNewReqDTO_sgs_data_MSGTYPE SGSMO
#define RealDataNewReqDTO_tgs_data_MSGTYPE TGSMO
#define RealDataNewReqDTO_pv_data_MSGTYPE PvMO

#define RealDataNewResDTO_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    cp,                2) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        3) \
X(a, STATIC,   SINGULAR, INT32,    offset,            4) \
X(a, STATIC,   SINGULAR, INT32,    time,              5)
#define RealDataNewResDTO_CALLBACK pb_default_field_callback
#define RealDataNewResDTO_DEFAULT NULL

extern const pb_msgdesc_t MeterMO_msg;
extern const pb_msgdesc_t RpMO_msg;
extern const pb_msgdesc_t RSDMO_msg;
extern const pb_msgdesc_t SGSMO_msg;
extern const pb_msgdesc_t TGSMO_msg;
extern const pb_msgdesc_t PvMO_msg;
extern const pb_msgdesc_t RealDataNewReqDTO_msg;
extern const pb_msgdesc_t RealDataNewResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MeterMO_fields &MeterMO_msg
#define RpMO_fields &RpMO_msg
#define RSDMO_fields &RSDMO_msg
#define SGSMO_fields &SGSMO_msg
#define TGSMO_fields &TGSMO_msg
#define PvMO_fields &PvMO_msg
#define RealDataNewReqDTO_fields &RealDataNewReqDTO_msg
#define RealDataNewResDTO_fields &RealDataNewResDTO_msg

/* Maximum encoded size of messages (where known) */
/* RealDataNewReqDTO_size depends on runtime parameters */
/* RealDataNewResDTO_size depends on runtime parameters */
#define MeterMO_size                             285
#define PvMO_size                                88
#define REALTIMEDATANEW_PB_H_MAX_SIZE            MeterMO_size
#define RSDMO_size                               88
#define RpMO_size                                55
#define SGSMO_size                               155
#define TGSMO_size                               225

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
