/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "RealtimeDataNew.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MeterMO, MeterMO, AUTO)


PB_BIND(RpMO, RpMO, AUTO)


PB_BIND(RSDMO, RSDMO, AUTO)


PB_BIND(SGSMO, SGSMO, AUTO)


PB_BIND(TGSMO, TGSMO, AUTO)


PB_BIND(PvMO, PvMO, AUTO)


PB_BIND(RealDataNewReqDTO, RealDataNewReqDTO, 2)


PB_BIND(RealDataNewResDTO, RealDataNewResDTO, AUTO)



