// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

// The referenced values are generated by pio-scripts/auto_firmware_version.py

extern const char* __COMPILED_GIT_HASH__;
extern const char* __COMPILED_GIT_BRANCH__;
// extern const char *__COMPILED_DATE_TIME_UTC_STR__;
