name: Yarn Prettier

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "webapp/yarn.lock"

      - name: Install WebApp dependencies
        run: yarn --cwd webapp install --frozen-lockfile

      - name: Check Formatting
        run: yarn --cwd webapp prettier --check src/
